import type { MetadataRoute } from "next";

/**
 * /robots.txt — generated by Next.js from this file.
 *
 * Public site is open. The dashboard, the API routes, and the
 * embedded Sanity Studio are explicitly disallowed because there's
 * nothing useful for crawlers to index there (and we don't want
 * Studio appearing in Google results).
 */
function siteUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) return process.env.NEXT_PUBLIC_SITE_URL;
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  return "http://localhost:3000";
}

export default function robots(): MetadataRoute.Robots {
  const base = siteUrl();
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/dashboard", "/api", "/studio"],
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}
