import type { MetadataRoute } from "next";
import { client as readClient } from "@/lib/sanity/client";
import { groq } from "next-sanity";

/**
 * /sitemap.xml — generated by Next.js from this file at build time
 * and on each ISR revalidation.
 *
 * Combines static public routes with every dynamic slug from Sanity.
 * Failure-tolerant: if Sanity is unreachable when the sitemap is
 * generated we still return the static routes instead of 500-ing
 * the entire page.
 */

function siteUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) return process.env.NEXT_PUBLIC_SITE_URL;
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  return "http://localhost:3000";
}

const SLUGS_QUERY = groq`{
  "messages": *[_type == "message" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "worship":  *[_type == "worshipSession" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "tracks":   *[_type == "track" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "tips":     *[_type == "tip" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "books":    *[_type == "book" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "assemblies": *[_type == "assembly" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "events":   *[_type == "event" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "meetings": *[_type == "meeting" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "pages":    *[_type == "page" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt },
  "posts":    *[_type == "post" && defined(slug.current)]{ "slug": slug.current, "_updatedAt": _updatedAt }
}`;

type SlugRow = { slug: string; _updatedAt: string };

type SlugBundle = {
  messages: SlugRow[];
  worship: SlugRow[];
  tracks: SlugRow[];
  tips: SlugRow[];
  books: SlugRow[];
  assemblies: SlugRow[];
  events: SlugRow[];
  meetings: SlugRow[];
  pages: SlugRow[];
  posts: SlugRow[];
};

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const base = siteUrl();
  const now = new Date();

  // Static routes that don't depend on Sanity data. Listed first so
  // they always appear even if the GROQ fetch below fails.
  const staticRoutes: MetadataRoute.Sitemap = [
    { url: `${base}/`, lastModified: now, changeFrequency: "weekly", priority: 1 },
    { url: `${base}/resources`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/resources/messages`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${base}/resources/worship`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${base}/resources/music`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${base}/resources/tips`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${base}/shop`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/assemblies`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/meetings`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/events`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${base}/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${base}/give`, lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/live`, lastModified: now, changeFrequency: "weekly", priority: 0.6 },
    { url: `${base}/members/join`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
  ];

  let dynamicRoutes: MetadataRoute.Sitemap = [];
  try {
    const data = await readClient.fetch<SlugBundle>(SLUGS_QUERY);

    // Helper: collapse a slug list into URL entries.
    const fromList = (
      list: SlugRow[] | undefined,
      pathPrefix: string,
      changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"],
      priority: number,
    ): MetadataRoute.Sitemap =>
      (list ?? []).map((row) => ({
        url: `${base}${pathPrefix}${row.slug}`,
        lastModified: row._updatedAt ? new Date(row._updatedAt) : now,
        changeFrequency,
        priority,
      }));

    dynamicRoutes = [
      ...fromList(data.messages, "/resources/messages/", "monthly", 0.7),
      ...fromList(data.worship, "/resources/worship/", "monthly", 0.6),
      ...fromList(data.tracks, "/resources/music/", "monthly", 0.6),
      ...fromList(data.tips, "/resources/tips/", "monthly", 0.6),
      ...fromList(data.books, "/shop/", "monthly", 0.7),
      ...fromList(data.assemblies, "/assemblies/", "monthly", 0.7),
      ...fromList(data.events, "/events/", "weekly", 0.6),
      ...fromList(data.meetings, "/meetings/", "monthly", 0.6),
      ...fromList(data.pages, "/", "monthly", 0.7),
      ...fromList(data.posts, "/blog/", "monthly", 0.6),
    ];
  } catch (err) {
    // Don't 500 the whole sitemap if Sanity blips — just log and
    // ship the static routes so Google still has something.
    console.error("[sitemap] Sanity fetch failed:", err);
  }

  return [...staticRoutes, ...dynamicRoutes];
}
